### ISSUE TITLE
Scene 프리뷰

### ISSUE THREAD

**Issue by minzy213** [minzy213/bae_bi#5]
**Main**
---
![image](https://github.com/minzy213/bae_bi/assets/43122045/62227cbb-d582-448a-b68a-96761467e3a1)

로고, 카테고리 버튼
(시각화, 추후 구체화)

> category (list)[
> 아래 내용을 dictionary list로 묶어서 전달
> 'name': 리스트에 표출될 카테고리 이름 ex) 치킨
> 'url': 버튼 누르면 이동할 해당 카테고리 url. ex) chicken
> 'img_path': 버튼에 표출될 이미지 url
> ]

---
**List**
--
![image](https://github.com/minzy213/bae_bi/assets/43122045/fb86ccba-9ea5-4b39-ab1a-c2411a20f47a)

카테고리 이름 (정렬 버튼)
브랜드 이름, 할인 정보
비교 메뉴 바구니

> cat_list [
> 'name': 최상단에 표출될 카테고리 이름. ex) 치킨
> 'store_list': [{'name', 'coupon'}] : 표출될 가게 정보 리스트, [가게 이름, 쿠폰 정보]
> ex) [BHC 동판교점', '요기요 5% 할인'
> ]

---
**Detail**
--
![image](https://github.com/minzy213/bae_bi/assets/43122045/88a911f6-3839-4833-b2d8-26021a5e1004)

브랜드 이름
어플별 배달 시간/요금, 쿠폰 정보
메뉴 리스트, 원가, 최종 할인가
체크버튼 누르면 비교 바구니에 넣는다

리뷰 남기기
브랜드 로고, ID, 별점, 리뷰

>Detail (dict)
> 'name': 최상단에 표출될 점포 이름. ex) BHC 동판교점
> 'service': [] 해당 점포가 등록된 어플 리스트. ex) [배민, 요기요]
> 'time': [] 어플별 배달 시간 리스트. 순서는 service에서 전달한 어플 순서. ex)[45~55분, 53~55분]
> 'fee': [] 어플별 배달 요금 리스트. 순서는 service에서 전달한 어플 순서. ex) [2,300원, 2,500원]
> 'coupon':[] 어플별 쿠폰 정보 리스트. 순서는 service에서 전달한 어플 순서. 없으면 빈칸 전달. ex) [1,000원 할인, '']

> 'menu_list'[
> {'name', 'price', 'info', 'thumbnail_path'}
> ]

> 'review_list'[
> {'author', 'content', 'rate', 'img_path', 'created_at', 'menu'},
> 작성자 이름, 리뷰 내용, 별점, 리뷰 이미지, 주문한 메뉴
> ]

---
Login/Logout
---

**Comment by minzy213** [comment]
Detail 화면의 메뉴 리스트에서 체크 시 비교 바구니에 넣도록 회의했는데, 
모든 메뉴에 체크버튼이 떠있는게 안예쁘다.
별도 화면에서 비교 바구니에 넣도록 되면 좋을 것 같다.

**Comment by codernoah404** [comment]
체크박스 없이 해당 메뉴 이름을 클릭하면 바구니에 추가 되도록 만들고 담아놓은 바구니에서 없앨 수 있도록 만드는 건 어떨까요

**Comment by Grivv** [comment]
메뉴별 썸네일 사진을 넣으면 어떨까요? 메뉴 이미지도 크롤링할까 해서요!
그리고 리뷰별로 (아니면 점포별로) 별점 정보도 추가하면 어떨까요?

**Comment by minzy213** [comment]
Scene별 새로운 이슈 생성
Main : https://github.com/minzy213/bae_bi/issues/11
List : https://github.com/minzy213/bae_bi/issues/13
Detail : https://github.com/minzy213/bae_bi/issues/14
